### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by becky2sawyer** [resume-diginori/resume-diginori.github.io#1]
``` bash
$ npm run serve

> vue-modern-resume@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
 10% building 2/5 modules 3 active ...server/client/index.js?http://localhostnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

```

**Comment by becky2sawyer** [comment]
https://github.com/vuejs/vue-cli/issues/6770#issuecomment-961307401

```
export NODE_OPTIONS=--openssl-legacy-provider
npm run serve
```
