### ISSUE TITLE
 ERROR  TypeError: tokens.indexOf is not a function

### ISSUE THREAD

**Issue by becky2sawyer** [resume-diginori/resume-diginori.github.io#2]
```
$ sh npm-run-build.sh

$ git commit -m "v0.1.0 the first space flight"
 > running pre-commit hook: lint-staged
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ❯ Running linters...
    ❯ Running tasks for *.{js,vue}
      ✖ vue-cli-service lint
        git add



✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  TypeError: tokens.indexOf is not a function
Occurred while linting /Users/m2/code/github/resume-diginori/resume-diginori.github.io/docs/js/chunk-vendors.8b1a7de6.js:1
TypeError: tokens.indexOf is not a function
Occurred while linting /Users/m2/code/github/resume-diginori/resume-diginori.github.io/docs/js/chunk-vendors.8b1a7de6.js:1
  at parseStatements (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint-plugin-varspacing/lib/util/findNextPunctuators.js:60:22)
  at module.exports (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint-plugin-varspacing/lib/util/findNextPunctuators.js:19:37)
  at expressionCheck (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint-plugin-varspacing/lib/rules/var-spacing.rule.js:41:7)
  at /Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/util/safe-emitter.js:45:58
  at Array.forEach (<anonymous>)
  at Object.emit (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/util/safe-emitter.js:45:38)
  at NodeEventGenerator.applySelector (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/util/node-event-generator.js:251:26)
  at NodeEventGenerator.applySelectors (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/util/node-event-generator.js:280:22)
  at NodeEventGenerator.enterNode (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/util/node-event-generator.js:294:14)
  at CodePathAnalyzer.enterNode (/Users/m2/code/github/resume-diginori/resume-diginori.github.io/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)

pre-commit hook failed (add --no-verify to bypass)
```

**Comment by becky2sawyer** [comment]
# Let's just skip it's over

git commit -m "v0.1.0 the first space flight" --no-verify
git push

-> c62af62..d77ad6e  master -> master
